### ISSUE TITLE
Stella Glow Support

### ISSUE THREAD

**Issue by HallowSL** [MapStudioProject/CTR-Studio#1]
Samples: https://mega.nz/file/MsA2HbaD#mTZF-5isYb1Z43KtPsKoyLp7oJ_aayzyWnyWbA7D5-k

The only program that supports the compression this game uses currently is https://github.com/gdkchan/Ohana3DS-Rebirth (It's dae/smd exports have always been hit or miss.)

**Comment by KillzXGaming** [comment]
Should load now, just no compressing back yet
