### ISSUE TITLE
Pokemon Omega Ruby: Issues with Exporting and Importing Greninja's model

### ISSUE THREAD

**Issue by SinaMegapolis** [MapStudioProject/CTR-Studio#10]
Issues:
1. Greninja model's colors become more lit and less saturated when exported as DAE and re-imported (whether directly or indirectly), unsure if this is an issue with Materials
2. If the model is passed through Blender, the Head will detach from the rig and float in the air, and some of the body will be distorted 

![In-game Picture to demonstrate](https://user-images.githubusercontent.com/24959713/189744694-9cc51896-99a9-4d2c-b7ac-7615452ad7ea.png)
![more pictures](https://user-images.githubusercontent.com/24959713/189746481-1e286ee3-aa55-4bb8-a468-450100342ae6.png)
![even more pictures](https://user-images.githubusercontent.com/24959713/189746536-371432a7-6fc8-422f-b7c7-7916d3f0b0fc.png)

How to reproduce both issues at the same time:
1. Extract Greninja's model from Omega Ruby (a/0/0/8/7131/pm0725_00.bch)
2. Open in CTR Studio, export the model as .dae
3. Open the .dae in Blender 3.3 and export as .dae
4. While back in CTR Studio, replace the model with the .dae file exported from Blender
5. Save the BCH and repack
6. Use the repacked GARC container as a LayeredFS mod in Citra

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/c9f50ad582c2aa00ac5ad2016f3be6af8a87272c

Rigging being a blender problem (buggy dae exporter) so I will close this for now. Hopefully blender will play nicer if gltf gets added
