### ISSUE TITLE
Render Layer Changes not Saving

### ISSUE THREAD

**Issue by ScottyBody8** [MapStudioProject/CTR-Studio#12]

**Comment by KillzXGaming** [comment]
Is this for BCRES or BCH? Where was this edited from, the model UI or materials?

**Comment by ScottyBody8** [comment]
It is for BCRES, edited in materials

**Comment by ScottyBody8** [comment]
![20220922_191205](https://user-images.githubusercontent.com/112992481/191867174-be044bc0-21b2-4eb3-9a98-f29faaaccd79.jpg)

This fence texture was set to translucent and in the translucent layer. The skybox can be seen through it, but all of the other geometry is occluded when looking through that texture

**Comment by ScottyBody8** [comment]
![20220922_191553](https://user-images.githubusercontent.com/112992481/191867503-f24cc67e-86f7-4689-8d23-ac31cc10e0f9.jpg)
![20220922_191625](https://user-images.githubusercontent.com/112992481/191867504-0b43bb8b-92e4-49ff-ae4f-554a1afaf794.jpg)

Images showing occluded geometry and other translucent textures visible when looking through

**Comment by KillzXGaming** [comment]
Does it revert or stay when reopened in the tool?

**Comment by ScottyBody8** [comment]
The tool always reverts the render layer to opaque when reopening

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/2c151dc5a03b01eeca2fd33f04c21d99e008b39a
