### ISSUE TITLE
BCRES : Support loading/saving scene data

### ISSUE THREAD

**Issue by milesthecreator** [MapStudioProject/CTR-Studio#13]
The bcmdl file fails to open, attached the file and log.
[log.txt](https://github.com/MapStudioProject/CTR-Studio/files/9741433/log.txt)
[DownLoad.bcmdl](https://drive.google.com/file/d/1-0dglESctpNPYBelpXnOuvaykCt3Mg5Q/view?usp=drivesdk)

**Comment by KillzXGaming** [comment]
Will open now. https://github.com/MapStudioProject/CTR-Studio/commit/680b1b4f91b35f8d24e4bb6382e5ee7048fc2f60 . Will however not save properly atm, scene data is not loaded/saved yet.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/57cf3c4df71fd976881d393359d666a02f281c3a
