### ISSUE TITLE
Application crashing at start?

### ISSUE THREAD

**Issue by Mooshroomdude250** [MapStudioProject/CTR-Studio#14]
Hey there. I just wanted to let you know that the latest build of this project I was really looking forward to use crashes at start. Is there any way to fix this bug?

**Comment by KillzXGaming** [comment]
Can you open a command prompt (search cmd in windows search bar and open it) then drag/drop the tool into it and press enter. Should show any possible errors.

**Comment by Mooshroomdude250** [comment]
It showed that I don't have .NET framework 6.0.8 despite me having said application. Tried uninstalling it, doesn't seem to recognize it.

**Comment by KillzXGaming** [comment]
You need the [desktop x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer) version of it.

**Comment by Mooshroomdude250** [comment]
Now it boots up, but all that it shows is a grey screen. (Tried dragging and dropping the ROM file (both .cia and .3ds), doesn't seem to work)
