### ISSUE TITLE
Can't open Pokemon ORAS map files

### ISSUE THREAD

**Issue by ACIDULATED** [MapStudioProject/CTR-Studio#15]
You can't open map files from romfs/a/0/3/9.

**Comment by KillzXGaming** [comment]
Need a sample file to test

**Comment by KillzXGaming** [comment]
![image](https://user-images.githubusercontent.com/13475262/229245622-806506ed-e491-45a7-9b47-f7fda0f8f949.png)

I assume they load fine now and is fixed
