### ISSUE TITLE
Exported bch files freeze on 3ds (ORAS)

### ISSUE THREAD

**Issue by RottingCrow** [MapStudioProject/CTR-Studio#18]
I've been trying to import an edited battle model into a/1/3/3/dec_25, however something in the way CTR studio exports causes freezing on console. I opened an unedited file, which normally works on 3ds, exported it to bch using CTR studio, and imported it back onto 3ds and the game freezes when trying to load it. I don't know if this is a general issue or related specifically to that garc, as i haven't tested any other garc files.

Edit: should add, exported files work perfectly with emulators like citra, the issue only occurs on 3ds

**Comment by RottingCrow** [comment]
should add, model works perfectly fine and causes no issues in emulators like citra, the issue is only with the 3ds

**Comment by KillzXGaming** [comment]
Possibly fixed now https://github.com/MapStudioProject/CTR-Studio/commit/0b4000ecb39cee073a7b2b184c9c882ac3489b46. Feel free to re open if still occurs
