### ISSUE TITLE
Improper weighting of models upon importing to BCMDL

### ISSUE THREAD

**Issue by gitduohub** [MapStudioProject/CTR-Studio#19]
Hello, there is a specific issue I am having with importing models to Mario Kart 7.

Within Blender, everything is fine. But with the import within CTR Studio, it seems that it weights every piece of geometry to one bone, but only on certain bones (e.g. the spine bone has the whole model weighted when it is not supposed to.) Other bones are unaffected; it seems to be happening with only one bone.

Image shown below for clarification on the issue.

![image](https://user-images.githubusercontent.com/30156280/203586845-65539fd5-3f78-4f25-bacb-86ef84958483.png)

**Comment by KillzXGaming** [comment]
I belive this is more of a viewing bug with weights as a vertex cannot be rigged fully by multiple bones. Could you select an animation to test the rig?

**Comment by gitduohub** [comment]
The animations seem to be working fine, all segments of the model move depending on the rig. Seems like it is a bug in viewing the model in the weights shading mode.

Testing in-game now, seeing if more problems occur or not.

**Comment by gitduohub** [comment]
Tested in-game, works without issues. Seems like it was truly just a visual bug.
