### ISSUE TITLE
BCH doesnt open

### ISSUE THREAD

**Issue by XLuma** [MapStudioProject/CTR-Studio#2]
For some reason, trying to open a .bch model makes the toolbar dissapear with no further feedback from the program. It is no crashing, it just doesnt renders anything.

If needed, I can link the BCH used. It comes from Pokemon ORAS

**Comment by KillzXGaming** [comment]
Need a bch sample

**Comment by XLuma** [comment]
This is from ORAS, it is Venusaur's model https://cdn.discordapp.com/attachments/972952138084909136/1016512061381025923/pm0003_00.bch

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/f58c2ca2a55a14b70500ee7ef3d5ac738e099006
