### ISSUE TITLE
Support for copying/pasting material User Data block?

### ISSUE THREAD

**Issue by Century-300** [MapStudioProject/CTR-Studio#20]
Hey there, sorry to bother but I wanted to request a feature for the tool.
I've been using CTR Studio for model edits in PersonaQ2, but the models themselves require a number of user properties to be applied to the material for it to work properly. Individually adding each one can be kind of a hassle so I wanted to ask if it would be possible to add support for copying the user data from other materials or at least saving the user data as part of a material preset.

![image](https://user-images.githubusercontent.com/74802102/204043594-a019794d-37a7-456c-9302-79a71812bb75.png)

**Comment by KillzXGaming** [comment]
If it uses BCH, that should already support export/replacing through json

**Comment by KillzXGaming** [comment]
This has been fixed for BCRES so both formats export and copy user data now
