### ISSUE TITLE
mesh precision inaccuracies?

### ISSUE THREAD

**Issue by steventylerseanherr** [MapStudioProject/CTR-Studio#22]
seems any imported meshs for bch has very slightly off verts compared to the original mesh AND the generated dae
resulting in very fine lines between meshes that have have exact same vert coordinates
![image](https://user-images.githubusercontent.com/48705919/212608636-44f30ff8-85be-4758-a6b6-4adaec7f3073.png)
this test was with link.bch. left is the reimported mode, right is original

i exported and reimported the mesh and now the verts that make up the mouth (or head?) mesh edges are off just enough to cause 
 seam problems ingame
edit: sorry not a very good picture
but those three black pixels is a seam where the head object meets the mouth object
ingame that looks like occasional black pixels on the mesh depending on view angle
and its REALLY noticeable at the native 3ds resolution

**Comment by steventylerseanherr** [comment]
its something to do with the normals?
i rejoined the mesh back to one whole piece and the problem was still there
and only after recalculating normals was it fixed

**Comment by steventylerseanherr** [comment]
i somehow fix it?
in blender the model was fine
and in any other 3d viewer the exported dae was always fine
but in ctr studio it had the seam

well after (re)recalculating the normals
the seams gone
entirely
so issue solved i guess?
imma close this unless there actually IS a problem

**Comment by steventylerseanherr** [comment]
ok after a retry the problem came back
and ive learned something
with links vanilla model his head and his body is 1 mesh
but if my custom model is like that (head and body as the same mesh)
then i get these seams
![image](https://user-images.githubusercontent.com/48705919/213431763-a2027419-c620-4ade-bc41-39b180881c7a.png)
but if the head and body mesh are separated
no seams at all
![image](https://user-images.githubusercontent.com/48705919/213432058-e36a46e9-d54e-44ec-916a-73ce46ed8273.png)

im not going to reopen this issue as im not sure if its a ctrstudio issue or blender issue
but since the seams doesnt appear in other 3d programs
im assuming its something to do with ctr studio

**Comment by steventylerseanherr** [comment]
reopening as im back into 3ds modeling and the issues still present
ive exported and reimported entirely fresh models and it still results in seams
and the exported models dont seem to have anything wrong with them in blender
so id assume its something to do with how ctrstudio imports the dae?

**Comment by steventylerseanherr** [comment]
i posted some more example pics on the discord if needed

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/666fe28e5053b61385a4329dcdc23729ab522e41
