### ISSUE TITLE
acnl trees are bugged after editing the fruit model

### ISSUE THREAD

**Issue by Pearlh2hoe** [MapStudioProject/CTR-Studio#23]
i edited the "fg_iteminside.bcres" file in acnl wich has the files for the fruit and trees, after editing the model with ctrstudio the trees bug out and the file always exports curropted.

**Comment by KillzXGaming** [comment]
Which model in particular since there is atleast 100 inside?

**Comment by Pearlh2hoe** [comment]
specificlly the durian model

**Comment by KillzXGaming** [comment]
I think this is fixed now as of https://github.com/MapStudioProject/CTR-Studio/commit/88ae3c3a3c814d03dcc93b9f32fe3e45fabf017e but feel free to reopen if it occurs still.
