### ISSUE TITLE
Issue with opening some Dead or Alive Dimensions .bcmdl files

### ISSUE THREAD

**Issue by sheikproject** [MapStudioProject/CTR-Studio#28]
I can open some model files from this game correctly, but they are some exceptions:
![image](https://user-images.githubusercontent.com/122214049/230727070-9b34b49f-10c0-47ed-ba44-79e961e5869c.png)

But when i dissable the high poly face:
![image](https://user-images.githubusercontent.com/122214049/230727247-6ac159e1-339e-4528-a0b6-71436a953665.png)
I dont know why this occurs since i can open the same format file from other models just fine.

Im uploading this face model and a costume model that it have the same issue

**Comment by KillzXGaming** [comment]
Fixed. Model handled vertex data in a certain way that isn't often used. https://github.com/MapStudioProject/CTR-Studio/commit/6666c9709e8b60c702508fd872855ee6f53be6fc
