### ISSUE TITLE
Dae importing/exporting is buggy

### ISSUE THREAD

**Issue by Hezzol** [MapStudioProject/CTR-Studio#3]
Exporting a model (Pokemon X) as DAE from CTRStudio and then opening it in blender works, issue is once you re export from blender (as DAE again) the model looks weird, even if you didnt make changes (pic for reference, no changes)
![image](https://user-images.githubusercontent.com/92102317/188629198-29c2f33e-154b-45fb-9730-5d3defdcd85d.jpg)

**Comment by KillzXGaming** [comment]
Need the original .bch to check.

**Comment by Hezzol** [comment]
https://drive.google.com/file/d/1OVTkAW5eD0Ug_64zZ6GmzvkhaWX2NknC/view?usp=sharing here's the link

**Comment by KillzXGaming** [comment]
From what I can tell, this looks to be an issue with blender. It has proper weights on import, then it just breaks it from export.  3ds max on the other hand has no problems.
