### ISSUE TITLE
lut bugs on bch / external loaded luts?

### ISSUE THREAD

**Issue by steventylerseanherr** [MapStudioProject/CTR-Studio#33]
unsure what the actual cause or problem is but with albws models atleast
studio will not load luts from a separate .szs
albws luts are in /US/RegionBoot.szs/World/LUT/common_lut.bch
load that archive and open the .bch
then load a model from the archives in /Archive
in all my tests the model still renders with the stock lut

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/e1ff82c6a3548cb2692799fbe1b5158121baad20
