### ISSUE TITLE
hilo encoding format bug

### ISSUE THREAD

**Issue by steventylerseanherr** [MapStudioProject/CTR-Studio#35]
fruityloops ran into this one and more info can be found on the discord server
starting from here: https://discord.com/channels/1034629789128065044/1034630843488014336/1119787766105002035
and train found the problem: https://discord.com/channels/1034629789128065044/1034630843488014336/1119789891614687352

ps: sorry for making so many bug reports so suddenly
just making sure they dont get buried in the discord

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/b709e3470e2c3be8d126a98542ec5252aee34bbc
