### ISSUE TITLE
.FBX Model Import Crash

### ISSUE THREAD

**Issue by TZGaming** [MapStudioProject/CTR-Studio#4]
When trying to import an FBX model, the program freezes for a bit and then crashes, I hope this will be fixed, because more people seem to have this issue as well.

**Comment by CyberYoshi64** [comment]
It's usually from trying to import models into a new file. Replacing one appears to work mostly fine. Here's the crash log for it.
[CrashLog_133069504537229797.txt](https://github.com/MapStudioProject/CTR-Studio/files/9498361/CrashLog_133069504537229797.txt)

**Comment by KillzXGaming** [comment]
If it is fixed from https://github.com/MapStudioProject/CTR-Studio/commit/8c31da5a9b2ac6d28cbaa90b1a29f94a259249bf, I will close it for now. Reopen if it still presists.
