### ISSUE TITLE
[request] allow saving and loading animations as fbx

### ISSUE THREAD

**Issue by FlashlightET** [MapStudioProject/CTR-Studio#50]
i would like to mod animations but i am not rich enough to own maya, but have nine years experience in the free open source blender program. there are no converters for this anim format that i can find. i have tried to write an entire json importer for blender but i could not get the rotation to import correctly. thanks and sorry if i am being a pest

**Comment by Haynster** [comment]
did u ever figure it out

**Comment by KillzXGaming** [comment]
There is https://github.com/PositionWizard/Blender_io-scene-ANIM/releases which can be used to use .anim in maya.

Additionally gltf and smd can be used which blender supports. Fbx could be added in the near future as I upgraded the fbx importer/exporter to a new assimp version, which could work once animation conversion is setup.
