### ISSUE TITLE
Texcoord1_Translate does not work on game

### ISSUE THREAD

**Issue by Kinopiokuppa** [MapStudioProject/CTR-Studio#54]
Texcoord1_Translate does not work on game consoles and emulators in Material animation

**Comment by KillzXGaming** [comment]
Fixed as of latest. I think from https://github.com/MapStudioProject/CTR-Studio/commit/5a66c8c45aad4df0f94d5b20449b33a87ffe20c2 and https://github.com/MapStudioProject/CTR-Studio/commit/51af137239fa2c951b6f57acabe661326aa74873
